services:
    video.command:
        class: Application\UseCase\Video\VideoCommand
        arguments:
          - '@video.factory'
          - '@video.repository'

    video.query:
        class: Application\UseCase\Video\VideoQuery
        arguments:
          - '@video.repository'

    import.command:
        class: Application\UseCase\ImportCommand
        arguments:
          - '@parser.command'
          - '@video.command'
